# Price of Used Toyota Corolla Cars(LogReg solution)

## **Target : Price**

    Id: Уникальный идентификатор для каждого автомобиля.
    Model: Модель Toyota Corolla.
    Price: Цена продажи подержанного автомобиля.
    Age_08_04: Возраст автомобиля в месяцах по состоянию на август 2004 года.
    Mfg_Month: Месяц производства автомобиля.
    Mfg_Year: Год производства автомобиля.
    KM: Пробег автомобиля в километрах.
    Fuel_type: Тип топлива (например, бензин, дизель).
    HP: Лошадиные силы, мера мощности двигателя.
    Met_Color: Бинарный индикатор металлической краски (0 = Нет, 1 = Да).
    Color: Цвет кузова автомобиля.
    Automatic: Бинарный индикатор автоматической коробки передач (0 = Нет, 1 = Да).
    CC: Объем двигателя в кубических сантиметрах.
    Doors: Количество дверей автомобиля.
    Cylinders: Количество цилиндров в двигателе.
    Gears: Количество передач в коробке передач.
    Quarterly: Ежеквартальный налог на автомобиль.
    Weight: Вес автомобиля.
    Mfr_Guarantee: Бинарный индикатор гарантии производителя (0 = Нет, 1 = Да).
    BOVAG_Guarantee: Бинарный индикатор гарантии BOVAG (0 = Нет, 1 = Да).
    Guarantee_Period: Срок гарантии в месяцах.
    ABS: Бинарный индикатор антиблокировочной тормозной системы (0 = Нет, 1 = Да).
    Airbag_1: Бинарный индикатор наличия подушки безопасности 1 (0 = Нет, 1 = Да).
    Airbag_2: Бинарный индикатор наличия подушки безопасности 2 (0 = Нет, 1 = Да).
    Airco: Бинарный индикатор кондиционера (0 = Нет, 1 = Да).
    Automatic_airco: Бинарный индикатор автоматического кондиционера (0 = Нет, 1 = Да).
    Boardcomputer: Бинарный индикатор наличия бортового компьютера (0 = Нет, 1 = Да).
    CD_Player: Бинарный индикатор наличия CD-плеера (0 = Нет, 1 = Да).
    Central_Lock: Бинарный индикатор центрального замка (0 = Нет, 1 = Да).
    Powered_Windows: Бинарный индикатор электростеклоподъемников (0 = Нет, 1 = Да).
    Power_Steering: Бинарный индикатор гидроусилителя руля (0 = Нет, 1 = Да).
    Radio: Бинарный индикатор наличия радио (0 = Нет, 1 = Да).
    Mistlamps: Бинарный индикатор противотуманных фар (0 = Нет, 1 = Да).
    Sport_Model: Бинарный индикатор спортивной модели (0 = Нет, 1 = Да).
    Backseat_Divider: Бинарный индикатор разделителя заднего сиденья (0 = Нет, 1 = Да).
    Metallic_Rim: Бинарный индикатор металлических дисков (0 = Нет, 1 = Да).
    Radio_cassette: Бинарный индикатор радиокассетного плеера (0 = Нет, 1 = Да).
    Parking_Assistant: Бинарный индикатор парковочного ассистента (0 = Нет, 1 = Да).
    Tow_Bar: Бинарный индикатор наличия фаркопа (0 = Нет, 1 = Да).

In [74]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV, KFold

from sklearn.preprocessing import OrdinalEncoder

from sklearn.tree import plot_tree

from sklearn.pipeline import Pipeline

In [75]:
df = pd.read_csv('ToyotaCorolla.csv')

# <center>EDA</center>

In [76]:
df.head()

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,1,0,0,0,1,0,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0

In [77]:
df.info() # Много признаков

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Model              1436 non-null   str
 2   Price              1436 non-null   int64
 3   Age_08_04          1436 non-null   int64
 4   Mfg_Month          1436 non-null   int64
 5   Mfg_Year           1436 non-null   int64
 6   KM                 1436 non-null   int64
 7   Fuel_Type          1436 non-null   str
 8   HP                 1436 non-null   int64
 9   Met_Color          1436 non-null   int64
 10  Color              1436 non-null   str
 11  Automatic          1436 non-null   int64
 12  CC                 1436 non-null   int64
 13  Doors              1436 non-null   int64
 14  Cylinders          1436 non-null   int64
 15  Gears              1436 non-null   int64
 16  Quarterly_Tax      1436 non-null   int64
 17  Weight             1436 non-null   int64
 18  Mfr_Guarantee      1436 non-null   int64
 19  BOVAG_Guarantee    1436 non-null   int64
 20  Guarantee_Period   1436 non-null   int64
 21  ABS                1436 non-null   int64
 22  Airbag_1           1436 non-null   int64
 23  Airbag_2           1436 non-null   int64
 24  Airco              1436 non-null   int64
 25  Automatic_airco    1436 non-null   int64
 26  Boardcomputer      1436 non-null   int64
 27  CD_Player          1436 non-null   int64
 28  Central_Lock       1436 non-null   int64
 29  Powered_Windows    1436 non-null   int64
 30  Power_Steering     1436 non-null   int64
 31  Radio              1436 non-null   int64
 32  Mistlamps          1436 non-null   int64
 33  Sport_Model        1436 non-null   int64
 34  Backseat_Divider   1436 non-null   int64
 35  Metallic_Rim       1436 non-null   int64
 36  Radio_cassette     1436 non-null   int64
 37  Parking_Assistant  1436 non-null   int64
 38  Tow_Bar            1436 non-null   int64
dtypes: int64(36), str(3)
memory usage: 437.7 KB

In [78]:
df.isna().sum() # Пропусков нет, ура

Id                   0
Model                0
Price                0
Age_08_04            0
Mfg_Month            0
Mfg_Year             0
KM                   0
Fuel_Type            0
HP                   0
Met_Color            0
Color                0
Automatic            0
CC                   0
Doors                0
Cylinders            0
Gears                0
Quarterly_Tax        0
Weight               0
Mfr_Guarantee        0
BOVAG_Guarantee      0
Guarantee_Period     0
ABS                  0
Airbag_1             0
Airbag_2             0
Airco                0
Automatic_airco      0
Boardcomputer        0
CD_Player            0
Central_Lock         0
Powered_Windows      0
Power_Steering       0
Radio                0
Mistlamps            0
Sport_Model          0
Backseat_Divider     0
Metallic_Rim         0
Radio_cassette       0
Parking_Assistant    0
Tow_Bar              0
dtype: int64

In [79]:
df.describe().round()

,Id,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,HP,Met_Color,Automatic,CC,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,...,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0,1436.0
mean,722.0,10731.0,56.0,6.0,2000.0,68533.0,102.0,1.0,0.0,1577.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
std,416.0,3627.0,19.0,3.0,2.0,37506.0,15.0,0.0,0.0,424.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,1.0,4350.0,1.0,1.0,1998.0,1.0,69.0,0.0,0.0,1300.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,362.0,8450.0,44.0,3.0,1998.0,43000.0,90.0,0.0,0.0,1400.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
50%,722.0,9900.0,61.0,5.0,1999.0,63390.0,110.0,1.0,0.0,1600.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
75%,1081.0,11950.0,70.0,8.0,2001.0,87021.0,110.0,1.0,0.0,1600.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0
max,1442.0,32500.0,80.0,12.0,2004.0,243000.0,192.0,1.0,1.0,16000.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [80]:
print(df.columns)

Index(['Id', 'Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'Fuel_Type', 'HP', 'Met_Color', 'Color', 'Automatic', 'CC', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Parking_Assistant', 'Tow_Bar'],
      dtype='str')

In [81]:
for col in df.columns:

    col_unique_count = df[col].unique().size

    print(f'{col} : {col_unique_count} unique values')

Id : 1436 unique values
Model : 319 unique values
Price : 236 unique values
Age_08_04 : 77 unique values
Mfg_Month : 12 unique values
Mfg_Year : 7 unique values
KM : 1263 unique values
Fuel_Type : 3 unique values
HP : 12 unique values
Met_Color : 2 unique values
Color : 10 unique values
Automatic : 2 unique values
CC : 13 unique values
Doors : 4 unique values
Cylinders : 1 unique values
Gears : 4 unique values
Quarterly_Tax : 13 unique values
Weight : 59 unique values
Mfr_Guarantee : 2 unique values
BOVAG_Guarantee : 2 unique values
Guarantee_Period : 9 unique values
ABS : 2 unique values
Airbag_1 : 2 unique values
Airbag_2 : 2 unique values
Airco : 2 unique values
Automatic_airco : 2 unique values
Boardcomputer : 2 unique values
CD_Player : 2 unique values
Central_Lock : 2 unique values
Powered_Windows : 2 unique values
Power_Steering : 2 unique values
Radio : 2 unique values
Mistlamps : 2 unique values
Sport_Model : 2 unique values
Backseat_Divider : 2 unique values
Metallic_Rim : 2 unique values
Radio_cassette : 2 unique values
Parking_Assistant : 2 unique values
Tow_Bar : 2 unique values

# <center>Feature Engineering</center>

# Надо вытащить данные из Model                                     **WIP**

In [82]:
# Временно удалим название машины

df = df.drop('Model', axis=1)
df = df.drop('Id', axis=1)

In [83]:
categorial_cols = ['Fuel_Type', 'Color']

enc = OrdinalEncoder()

df[categorial_cols] = enc.fit_transform(df[categorial_cols])

print(df[categorial_cols])

      Fuel_Type  Color
0           1.0    2.0
1           1.0    6.0
2           1.0    2.0
3           1.0    1.0
4           1.0    1.0
...         ...    ...
1431        2.0    2.0
1432        2.0    4.0
1433        2.0    2.0
1434        2.0    4.0
1435        2.0    3.0

[1436 rows x 2 columns]

In [84]:
X = df.drop('Price', axis=True)
y = df['Price']

# Разделение на ТРИ части
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42)

In [92]:
rf_base = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    oob_score=True  # Включаем Out-of-Bag оценку
)

rf_base.fit(X_train, y_train)

train_pred = rf_base.predict(X_train)
val_pred = rf_base.predict(X_val)
test_pred = rf_base.predict(X_test)

# OOB оценка (встроенная)
oob_r2 = rf_base.oob_score_  # По умолчанию R²
print(f"OOB R²: {oob_r2:.4f}")

# Дополнительные метрики
print(f"\n--- На трейне ---")
print(f"  R²:   {r2_score(y_train, train_pred):.4f}")
print(f"  MAE:  {mean_absolute_error(y_train, train_pred):.2f}")
print(f"  RMSE: {np.sqrt(mean_squared_error(y_train, train_pred)):.2f}")

print("\n--- На валидации ---")
print(f"R² (коэф. детерминации): {r2_score(y_val, val_pred):.4f}")
print(f"MAE: {mean_absolute_error(y_val, val_pred):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_val, val_pred)):.4f}")

print("\n--- На тесте ---")
print(f"R²: {r2_score(y_test, test_pred):.4f}")
print(f"MAE: {mean_absolute_error(y_test, test_pred):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, test_pred)):.4f}")

OOB R²: 0.8988

--- На трейне ---
  R²:   0.9858
  MAE:  299.43
  RMSE: 426.68

--- На валидации ---
R² (коэф. детерминации): 0.9172
MAE: 813.7195
RMSE: 1069.0011

--- На тесте ---
R²: 0.9258
MAE: 764.3114
RMSE: 994.6951

In [90]:
# Берем первое дерево из леса
first_tree = rf_base.estimators_[0]

print(f"Всего деревьев в лесу: {len(rf_base.estimators_)}")
print(f"Глубина первого дерева: {first_tree.get_depth()}")
print(f"Количество листьев: {first_tree.get_n_leaves()}")

Всего деревьев в лесу: 100
Глубина первого дерева: 21
Количество листьев: 471

### Применим кросс-валидацию

In [87]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

rf_cv = RandomForestRegressor(random_state=42, n_jobs=-1, oob_score=True)

# обычный KFold
cv = KFold(n_splits=5, shuffle=True, random_state=42)

grid_search = GridSearchCV(
    estimator=rf_cv,
    param_grid=param_grid,
    cv=cv,
    scoring='neg_mean_absolute_error',  # Минимизируем MAE (или 'r2', 'neg_root_mean_squared_error')
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

for param, value in grid_search.best_params_.items():
    print(f"  {param}: {value}")

print(f"\nЛучший MAE на кросс-валидации: {-grid_search.best_score_:.2f}")

Fitting 5 folds for each of 144 candidates, totalling 720 fits
  max_depth: 15
  max_features: sqrt
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 200

Лучший MAE на кросс-валидации: 827.63

In [88]:
param_grid = {
    'max_depth': [5, 7, 10, 12, 15, None],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 5, 10],
    'max_features': [None, 'sqrt', 'log2']
}

tree = DecisionTreeRegressor(random_state=42)

#обычный KFold
cv = KFold(n_splits=5, shuffle=True, random_state=42)

grid_search = GridSearchCV(
    estimator=tree,
    param_grid=param_grid,
    cv=cv,
    scoring='neg_mean_absolute_error',  # минимизируем MAE
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

print(f"\nЛучшие параметры:")
for param, value in grid_search.best_params_.items():
    print(f"  {param}: {value}")
print(f"\nЛучший MAE на кросс-валидации: {-grid_search.best_score_:.2f}")

Fitting 5 folds for each of 288 candidates, totalling 1440 fits

Лучшие параметры:
  max_depth: 5
  max_features: None
  min_samples_leaf: 2
  min_samples_split: 2

Лучший MAE на кросс-валидации: 901.16

## 1. Разделение выборки

Подготовьте данные для обучения модели. 

**Обязательно объясните текстом:**
* **Сделали ли вы предобработку данных для случайного леса? Отличалась ли она от предобработки данных для линейной модели? Если до, то почему?**
    - Да, для случайного леса не требуется стандартизация, так как суть в обучении деревьев, а деревья делят данные не взирая на масштаб. А так же вместо one-hot я использовал label encoding.
* **Как именно вы разделили выборку?** 
    - 60% Train 20% Test 20% Validation
* **На сколько частей нужно делить выборку при использовании кросс-валидации?**
    - вручную на 2, но я использовал KFold, который делит много раз данные
* **Можно ли не использовать кросс-валидацию? Если да, то как делить выборку в таком случае?** 
    - можно, например если очень много данных, тогда нужно 60% Train 20% Test 20% Validation и следить за переобучением (разность Val И test)


## 2. Обучение моделей

Обучите случайный лес. Обучите одно дерево той же глубины, какую вы укажете в случайном лесе. Сравните результаты.

**Вопросы для анализа:**
* **Сравнение скорости:** сравните, какая модель обучалась быстрее. 
    - Дерево обучилось гораздо быстрее.
* **Можно ли добиться одинаковой или близкой к одинаковой скорости?**
    - Нельзя так как суть леса в обучении множества деревьев
* **Сравнение качества:** сравните результаты одного дерева и случайного леса. 
    - Лес значительно точнее (около 100 по MAE)